---
- name: Setup Fedora Server with Podman and MariaDB
  hosts: localhost
  become: yes
  tasks:

    - name: Update all system packages
      dnf:
        name: '*'
        state: latest

    - name: Install Podman
      dnf:
        name: podman
        state: present

    - name: Install Cockpit
      dnf:
        name: cockpit
        state: present

    - name: Install Cockpit Podman plugin
      dnf:
        name: cockpit-podman
        state: present

    - name: Ensure Cockpit service is started
      systemd:
        name: cockpit.socket
        state: started
        enabled: yes

    - name: Restart Cockpit service
      systemd:
        name: cockpit.socket
        state: restarted

    - name: Pull the latest MariaDB Podman image
      command:
        cmd: podman pull mariadb:latest
        creates: /var/lib/containers/storage/overlay
      register: mariadb_image

    - name: Display the result of the MariaDB image pull
      debug:
        msg: "MariaDB Podman image pulled successfully. Details: {{ mariadb_image }}"

    - name: Create Podman volume for MariaDB data
      command:
        cmd: podman volume create mariadb_data
        creates: /var/lib/containers/storage/volumes/mariadb_data
      register: mariadb_volume

    - name: Display the result of volume creation
      debug:
        msg: "MariaDB Podman volume created successfully. Details: {{ mariadb_volume }}"

    - name: Run MariaDB container with Podman
      command:
        cmd: >
          podman run -d
          --name mariadb
          --restart always
          -p 3306:3306
          -e MYSQL_ROOT_PASSWORD=your_root_password
          -e MYSQL_DATABASE=your_database_name
          -e MYSQL_USER=your_user
          -e MYSQL_PASSWORD=your_password
          -v mariadb_data:/var/lib/mysql
          mariadb:latest
        creates: /var/lib/containers/storage/overlay
      register: mariadb_container

    - name: Display the result of MariaDB container setup
      debug:
        msg: "MariaDB Podman container is up and running. Details: {{ mariadb_container }}"
